# Site settings
title: "Michael McKelligott"
description: "PhD Student at the University of Chicago Harris School of Public Policy"
theme: minimal

# Build settings
markdown: kramdown

# Navigation (Optional)
header_pages:
  - index.md
  - research.md
