# Site settings
title: "Michael McKelligott"
description: "PhD Student at the University of Chicago Harris School of Public Policy"
theme: cayman # You can change this to cayman, slate, minima, etc.

# GitHub and Social Links (optional)
github_username: mike-mck

# Build settings
markdown: kramdown
